-- Currency list: coins, tokens, and tradeable monetary items that are always looted regardless of other rules

local Base = require('loot_e9.lists._base')

return Base.new('currency', {
    { name='Green Stone of Minor Advancement' },
    { name='Frosty Stone of Hearty Advancement' },
    { name='Fiery Stone of Incredible Advancement' },
    { name='Epic Gemstone of Immortality' },
    { name='Overlords Anguish Stone' },
    { name='Moneybags - Bag of Platinum Pieces' },
    { name='Moneybags - Heavy Bag of Platinum!' },
    { name='Unidentified item' },
    { name='Bear Spray - Maximum Strength - Aim AWAY from face!' },
    { name='Token of Discord' },
    { name="Stone of Fusion's Horror" },
    { name='Timekeeper Credit Token - 50 Timekeeper Credits' },
    { name='Timekeeper Credit Token - 100 Timekeeper Credits' },
    { name='Timekeeper Credit Token - 500 Timekeeper Credits' },
    { name="Advancement Token - 50 AA's" },
    { name="Advancement Token - 100 AA's" },
    { name="Advancement Token - 500 AA's" },
    { name='Huge Bag of Platinum' },
    { name='Heavy Bag of Platinum' },
    { name='Ruby' },
    { name='Diamond' },
    { name='Blue Diamond' },
    { name='Black Pearl' },
    { name='Black Sapphire' },
    { name='Fire Emerald' },
    { name='Star Ruby' },
    { name='Sapphire' },
    { name='Curved Ikaav Fang' },
    { name='Scarred Kyv Flesh' },
    { name='Serpent-Like Huvul Tongue' },
    { name='Chipped Arrowhead' },
    { name='Sparking Lightning Spike' },
    { name='Tattooed Huvul Flesh' },
    { name='Dark Discordling Tongue' },
    { name='Broken Ukun Leash' },
    { name='Glowing Arrowheads' },
    { name='Slitted Ikaav Eye' },
    { name='Tattooed Discordling Hide' },
    { name='Umbracite Swarm Orb' },
    { name='Astrial Token' },
    { name='Deva Token' },
    { name='Mark of Valor' },
    { name='Stone of Advancement' },
    { name='Coin of the Realm' },
    { name='War Coin' },
    { name='Crystallized Experience' },
})
