-- Beasts tier: Beast Lord and pet-class progression gear

local Base = require('proloot.lists._base')

return Base.new('beasts', {
    { name='Primal Core of Gelid Creation' },
    { name='Primal Scales' },
    { name='Primal Hide' },
    { name='Primal Links' },
    { name='Primal Cloth' },
    { name='Leather Gauntlets Mold of the Gelid' },
    { name='Leather Sleeves Mold of the Gelid' },
    { name='Leather Bracer Mold of the Gelid' },
    { name='Leather Helm Mold of the Gelid' },
    { name='Leather Chest Mold of the Gelid' },
    { name='Leather Boots Mold of the Gelid' },
    { name='Leather Leggings Mold of the Gelid' },
    { name='Plate Sleeves Mold of the Gelid' },
    { name='Plate Chest Mold of the Gelid' },
    { name='Plate Leggings Mold of the Gelid' },
    { name='Plate Helm Mold of the Gelid' },
    { name='Plate Bracer Mold of the Gelid' },
    { name='Plate Gauntlets Mold of the Gelid' },
    { name='Plate Boots Mold of the Gelid' },
    { name='Chain Sleeves Mold of the Gelid' },
    { name='Chain Chest Mold of the Gelid' },
    { name='Chain Leggings Mold of the Gelid' },
    { name='Chain Helm Mold of the Gelid' },
    { name='Chain Bracer Mold of the Gelid' },
    { name='Chain Gauntlets Mold of the Gelid' },
    { name='Chain Boots Mold of the Gelid' },
    { name='Cloth Sleeves Mold of the Gelid' },
    { name='Cloth Chest Mold of the Gelid' },
    { name='Cloth Leggings Mold of the Gelid' },
    { name='Cloth Helm Mold of the Gelid' },
    { name='Cloth Bracer Mold of the Gelid' },
    { name='Cloth Gauntlets Mold of the Gelid' },
    { name='Cloth Boots Mold of the Gelid' },
})
